name: credevator
recipe: drupal9
config:
  webroot: docroot
  composer_version: '2.1.0'
  php: '8.0'
services:
  appserver:
    build:
      - composer install
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt