name: Build & lint project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          php_extensions: gd
          version: 2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Run BLT Tests
        run: blt validate